// Obey openapi.yaml

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries from the products table
  await knex('products').del();

  // Inserts seed entries for featured products
  await knex('products').insert([
    {
      id: 1,
      name: 'Raspberry Pi 4 Model B 4GB',
      description: 'Small single-board computer',
      category_id: 1,
      price: 49.99,
      image_url: '/images/pi4.jpg',
      stock: 50,
      is_featured: true,
    },
    {
      id: 2,
      name: 'ESP32 Dev Module',
      description: 'Wi-Fi + BLE microcontroller',
      category_id: 2,
      price: 6.5,
      image_url: '/images/esp32.jpg',
      stock: 150,
      is_featured: true,
    },
    {
      id: 3,
      name: '18650 Li-ion Battery',
      description: 'High capacity rechargeable cell',
      category_id: 3,
      price: 8.25,
      image_url: '/images/battery.jpg',
      stock: 300,
      is_featured: true,
    },
    {
      id: 4,
      name: 'USB-C PD 65W Charger',
      description: 'Fast charging for laptops & phones',
      category_id: 4,
      price: 24.0,
      image_url: '/images/charger.jpg',
      stock: 75,
      is_featured: true,
    },
    {
      id: 5,
      name: 'Raspberry Pi Zero 2 W',
      description: 'Ultra-small, quad-core 64-bit computer with wireless.',
      category_id: 1,
      price: 15.00,
      image_url: '/images/pi-zero-2-w.jpg',
      stock: 120,
      is_featured: false,
    },
    {
      id: 6,
      name: 'Arduino UNO R4 WiFi',
      description: 'The classic Arduino board, now with an ESP32-S3 for Wi-Fi.',
      category_id: 2,
      price: 27.50,
      image_url: '/images/arduino-uno-r4.jpg',
      stock: 80,
      is_featured: true,
    },
    {
      id: 7,
      name: '5V 3A Power Supply',
      description: 'Reliable power for your Raspberry Pi and other projects.',
      category_id: 3,
      price: 12.99,
      image_url: '/images/power-supply-5v.jpg',
      stock: 200,
      is_featured: false,
    },
    {
      id: 8,
      name: 'Breadboard (830-point)',
      description: 'Solderless breadboard for prototyping circuits.',
      category_id: 4,
      price: 5.50,
      image_url: '/images/breadboard.jpg',
      stock: 500,
      is_featured: false,
    },
    {
      id: 9,
      name: 'NVIDIA Jetson Nano Dev Kit',
      description: 'Powerful and compact AI computer for developers.',
      category_id: 1,
      price: 149.00,
      image_url: '/images/jetson-nano.jpg',
      stock: 30,
      is_featured: true,
    },
    {
      id: 10,
      name: 'Teensy 4.1',
      description: 'Extremely fast microcontroller with a wealth of I/O.',
      category_id: 2,
      price: 29.95,
      image_url: '/images/teensy-4-1.jpg',
      stock: 60,
      is_featured: false,
    },
    {
      id: 11,
      name: 'LiPo Battery Charger (TP4056)',
      description: 'Micro-USB module for charging single-cell LiPo batteries.',
      category_id: 3,
      price: 1.99,
      image_url: '/images/tp4056-charger.jpg',
      stock: 400,
      is_featured: false,
    },
    {
      id: 12,
      name: 'Jumper Wires (Assorted)',
      description: 'Pack of 40 male-to-male, male-to-female, and female-to-female wires.',
      category_id: 4,
      price: 6.99,
      image_url: '/images/jumper-wires.jpg',
      stock: 1000,
      is_featured: false,
    },
    {
      id: 13,
      name: 'BeagleBone Black',
      description: 'Community-supported development platform for developers and hobbyists.',
      category_id: 1,
      price: 55.00,
      image_url: '/images/beaglebone-black.jpg',
      stock: 45,
      is_featured: false,
    },
    {
      id: 14,
      name: 'Seeed Studio XIAO ESP32C3',
      description: 'Thumb-sized ESP32 board with Wi-Fi/BLE and battery charge support.',
      category_id: 2,
      price: 4.99,
      image_url: '/images/xiao-esp32c3.jpg',
      stock: 250,
      is_featured: true,
    },
    {
      id: 15,
      name: 'Buck Converter (LM2596)',
      description: 'Adjustable step-down voltage regulator module.',
      category_id: 3,
      price: 2.50,
      image_url: '/images/buck-converter.jpg',
      stock: 350,
      is_featured: false,
    },
    {
      id: 16,
      name: '16GB MicroSD Card with Adapter',
      description: 'Class 10 high-speed memory card for operating systems and storage.',
      category_id: 4,
      price: 7.99,
      image_url: '/images/microsd-card.jpg',
      stock: 150,
      is_featured: false,
    },
    {
      id: 17,
      name: 'Raspberry Pi Pico W',
      description: 'Low-cost microcontroller board with wireless from Raspberry Pi.',
      category_id: 2,
      price: 6.00,
      image_url: '/images/pi-pico-w.jpg',
      stock: 300,
      is_featured: false,
    },
    {
      id: 18,
      name: 'Solar Panel 6V 1W',
      description: 'Small solar panel for powering outdoor projects.',
      category_id: 3,
      price: 9.50,
      image_url: '/images/solar-panel.jpg',
      stock: 90,
      is_featured: false,
    },
    {
      id: 19,
      name: 'Ultrasonic Sensor (HC-SR04)',
      description: 'Provides distance measurement, great for robotics.',
      category_id: 4,
      price: 1.99,
      image_url: '/images/hc-sr04.jpg',
      stock: 400,
      is_featured: false,
    },
    {
      id: 20,
      name: 'Servo Motor (SG90)',
      description: 'Miniature servo for small-scale robotics and animatronics.',
      category_id: 4,
      price: 2.99,
      image_url: '/images/sg90-servo.jpg',
      stock: 600,
      is_featured: false,
    },
    {
      id: 21,
      name: '16x2 LCD Display with I2C',
      description: 'Blue character LCD with I2C interface for easy connection.',
      category_id: 4,
      price: 7.25,
      image_url: '/images/lcd-1602-i2c.jpg',
      stock: 120,
      is_featured: false,
    },
    {
      id: 22,
      name: 'Relay Module (2-Channel)',
      description: 'Control high-voltage devices with your microcontroller.',
      category_id: 2,
      price: 4.50,
      image_url: '/images/relay-module.jpg',
      stock: 180,
      is_featured: false,
    },
    {
      id: 23,
      name: 'Resistor Kit (Assorted)',
      description: 'A must-have kit with a wide range of common resistor values.',
      category_id: 4,
      price: 9.99,
      image_url: '/images/resistor-kit.jpg',
      stock: 200,
      is_featured: false,
    },
    {
      id: 24,
      name: 'LED Kit (Assorted Colors)',
      description: 'A variety of 5mm LEDs in red, green, blue, yellow, and white.',
      category_id: 4,
      price: 5.99,
      image_url: '/images/led-kit.jpg',
      stock: 300,
      is_featured: false,
    },
    {
      id: 25,
      name: 'Logic Level Shifter',
      description: 'Safely connect 3.3V and 5V devices. Bi-directional, 4-channel.',
      category_id: 2,
      price: 2.25,
      image_url: '/images/level-shifter.jpg',
      stock: 220,
      is_featured: false,
    },
    {
      id: 26,
      name: '9V Battery Snap Connector',
      description: 'Connector with leads for easily powering projects with a 9V battery.',
      category_id: 3,
      price: 0.99,
      image_url: '/images/9v-snap.jpg',
      stock: 800,
      is_featured: false,
    },
    {
      id: 27,
      name: 'HDMI to Micro-HDMI Cable',
      description: 'Connect your Raspberry Pi 4 to a standard HDMI display.',
      category_id: 4,
      price: 6.50,
      image_url: '/images/hdmi-micro-hdmi.jpg',
      stock: 130,
      is_featured: false,
    },
    {
      id: 28,
      name: 'USB to TTL Serial Adapter',
      description: 'Essential for debugging and programming microcontrollers.',
      category_id: 4,
      price: 4.75,
      image_url: '/images/usb-ttl.jpg',
      stock: 160,
      is_featured: false,
    },
    {
      id: 29,
      name: 'Adafruit Feather M4 Express',
      description: 'Powerful Cortex M4 board with CircuitPython support.',
      category_id: 2,
      price: 22.95,
      image_url: '/images/feather-m4.jpg',
      stock: 70,
      is_featured: false,
    },
    {
      id: 30,
      name: 'Raspberry Pi 5 8GB',
      description: 'The latest and most powerful Raspberry Pi available.',
      category_id: 1,
      price: 80.00,
      image_url: '/images/pi5.jpg',
      stock: 40,
      is_featured: true,
    }
  ]);

  // After seeding, we need to reset the primary key sequence to the max id,
  // so that new entries don't cause a primary key conflict.
  try {
    await knex.raw('SELECT setval(\'products_id_seq\', (SELECT MAX(id) from "products"));');
  } catch (error) {
    console.error("Could not reset 'products_id_seq' sequence. This is expected if you are not using PostgreSQL.", error.message);
  }
}
